server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Cette ligne est MAGIQUE : elle dit à Nginx de renvoyer vers index.html 
        # si la route (ex: /dashboard) n'est pas un fichier réel.
        try_files $uri $uri/ /index.html;
    }

    # Optionnel : Cache pour les assets statiques (JS/CSS)
    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}